In [ ]:
import pandas as pd
import numpy as np

In [69]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [82]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size = 0.3, random_state = 42)

In [84]:
n_cols = predictors_norm.shape[1]

In [94]:
from keras.models import Sequential
from keras.layers import Dense

# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [95]:
model = regression_model()
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - loss: 1589.0721 - val_loss: 1485.5400 - 560ms/epoch - 24ms/step
Epoch 2/100
23/23 - 0s - loss: 1567.7421 - val_loss: 1462.9982 - 66ms/epoch - 3ms/step
Epoch 3/100
23/23 - 0s - loss: 1541.9207 - val_loss: 1432.7249 - 64ms/epoch - 3ms/step
Epoch 4/100
23/23 - 0s - loss: 1504.9174 - val_loss: 1388.6375 - 65ms/epoch - 3ms/step
Epoch 5/100
23/23 - 0s - loss: 1450.3929 - val_loss: 1323.5870 - 70ms/epoch - 3ms/step
Epoch 6/100
23/23 - 0s - loss: 1372.6044 - val_loss: 1230.9125 - 78ms/epoch - 3ms/step
Epoch 7/100
23/23 - 0s - loss: 1263.7466 - val_loss: 1106.0004 - 73ms/epoch - 3ms/step
Epoch 8/100
23/23 - 0s - loss: 1111.2605 - val_loss: 927.9070 - 72ms/epoch - 3ms/step
Epoch 9/100
23/23 - 0s - loss: 904.4226 - val_loss: 710.1696 - 74ms/epoch - 3ms/step
Epoch 10/100
23/23 - 0s - loss: 677.8774 - val_loss: 505.9025 - 75ms/epoch - 3ms/step
Epoch 11/100
23/23 - 0s - loss: 483.7014 - val_loss: 362.3383 - 60ms/epoch - 3ms/step
Epoch 12/100
23/23 - 0s - loss: 359.1020 - val_loss: 288.2476 - 74ms/epoch - 3ms/step
Epoch 13/100
23/23 - 0s - loss: 289.1069 - val_loss: 249.6927 - 61ms/epoch - 3ms/step
Epoch 14/100
23/23 - 0s - loss: 249.0012 - val_loss: 224.3403 - 74ms/epoch - 3ms/step
Epoch 15/100
23/23 - 0s - loss: 224.3759 - val_loss: 207.2713 - 72ms/epoch - 3ms/step
Epoch 16/100
23/23 - 0s - loss: 209.5630 - val_loss: 196.6048 - 71ms/epoch - 3ms/step
Epoch 17/100
23/23 - 0s - loss: 198.1327 - val_loss: 189.4809 - 65ms/epoch - 3ms/step
Epoch 18/100
23/23 - 0s - loss: 190.3998 - val_loss: 184.5921 - 72ms/epoch - 3ms/step
Epoch 19/100
23/23 - 0s - loss: 184.1386 - val_loss: 180.0598 - 72ms/epoch - 3ms/step
Epoch 20/100
23/23 - 0s - loss: 179.0221 - val_loss: 175.3917 - 72ms/epoch - 3ms/step
Epoch 21/100
23/23 - 0s - loss: 174.3395 - val_loss: 171.8941 - 60ms/epoch - 3ms/step
Epoch 22/100
23/23 - 0s - loss: 170.2379 - val_loss: 168.4912 - 74ms/epoch - 3ms/step
Epoch 23/100
23/23 - 0s - loss: 165.8974 - val_loss: 165.1418 - 67ms/epoch - 3ms/step
Epoch 24/100
23/23 - 0s - loss: 162.4985 - val_loss: 161.0126 - 73ms/epoch - 3ms/step
Epoch 25/100
23/23 - 0s - loss: 158.3702 - val_loss: 157.8718 - 69ms/epoch - 3ms/step
Epoch 26/100
23/23 - 0s - loss: 155.1526 - val_loss: 154.2148 - 112ms/epoch - 5ms/step
Epoch 27/100
23/23 - 0s - loss: 151.9419 - val_loss: 151.5345 - 65ms/epoch - 3ms/step
Epoch 28/100
23/23 - 0s - loss: 148.6211 - val_loss: 148.3811 - 64ms/epoch - 3ms/step
Epoch 29/100
23/23 - 0s - loss: 145.2093 - val_loss: 144.9021 - 62ms/epoch - 3ms/step
Epoch 30/100
23/23 - 0s - loss: 142.0920 - val_loss: 142.8920 - 66ms/epoch - 3ms/step
Epoch 31/100
23/23 - 0s - loss: 139.0240 - val_loss: 139.5502 - 65ms/epoch - 3ms/step
Epoch 32/100
23/23 - 0s - loss: 136.3406 - val_loss: 136.8324 - 59ms/epoch - 3ms/step
Epoch 33/100
23/23 - 0s - loss: 133.3390 - val_loss: 133.9437 - 73ms/epoch - 3ms/step
Epoch 34/100
23/23 - 0s - loss: 130.4221 - val_loss: 131.5724 - 72ms/epoch - 3ms/step
Epoch 35/100
23/23 - 0s - loss: 127.3529 - val_loss: 128.8020 - 74ms/epoch - 3ms/step
Epoch 36/100
23/23 - 0s - loss: 124.4181 - val_loss: 126.3870 - 69ms/epoch - 3ms/step
Epoch 37/100
23/23 - 0s - loss: 121.6400 - val_loss: 123.5394 - 59ms/epoch - 3ms/step
Epoch 38/100
23/23 - 0s - loss: 119.0827 - val_loss: 121.6902 - 72ms/epoch - 3ms/step
Epoch 39/100
23/23 - 0s - loss: 116.2091 - val_loss: 118.3028 - 65ms/epoch - 3ms/step
Epoch 40/100
23/23 - 0s - loss: 113.7778 - val_loss: 116.9142 - 75ms/epoch - 3ms/step
Epoch 41/100
23/23 - 0s - loss: 110.9976 - val_loss: 114.7642 - 73ms/epoch - 3ms/step
Epoch 42/100
23/23 - 0s - loss: 108.8796 - val_loss: 112.2227 - 67ms/epoch - 3ms/step
Epoch 43/100
23/23 - 0s - loss: 105.9527 - val_loss: 110.5809 - 72ms/epoch - 3ms/step
Epoch 44/100
23/23 - 0s - loss: 103.9456 - val_loss: 108.0325 - 61ms/epoch - 3ms/step
Epoch 45/100
23/23 - 0s - loss: 101.4321 - val_loss: 106.0599 - 69ms/epoch - 3ms/step
Epoch 46/100
23/23 - 0s - loss: 98.8726 - val_loss: 103.8734 - 74ms/epoch - 3ms/step
Epoch 47/100
23/23 - 0s - loss: 96.0936 - val_loss: 101.8832 - 69ms/epoch - 3ms/step
Epoch 48/100
23/23 - 0s - loss: 93.8492 - val_loss: 99.4787 - 72ms/epoch - 3ms/step
Epoch 49/100
23/23 - 0s - loss: 91.3503 - val_loss: 98.7693 - 60ms/epoch - 3ms/step
Epoch 50/100
23/23 - 0s - loss: 89.0287 - val_loss: 96.6144 - 71ms/epoch - 3ms/step
Epoch 51/100
23/23 - 0s - loss: 87.0515 - val_loss: 94.1550 - 60ms/epoch - 3ms/step
Epoch 52/100
23/23 - 0s - loss: 84.6812 - val_loss: 91.9525 - 76ms/epoch - 3ms/step
Epoch 53/100
23/23 - 0s - loss: 82.8284 - val_loss: 90.3386 - 71ms/epoch - 3ms/step
Epoch 54/100
23/23 - 0s - loss: 80.6968 - val_loss: 87.6645 - 74ms/epoch - 3ms/step
Epoch 55/100
23/23 - 0s - loss: 79.0470 - val_loss: 86.0757 - 72ms/epoch - 3ms/step
Epoch 56/100
23/23 - 0s - loss: 77.1591 - val_loss: 84.1177 - 77ms/epoch - 3ms/step
Epoch 57/100
23/23 - 0s - loss: 75.7264 - val_loss: 81.8515 - 75ms/epoch - 3ms/step
Epoch 58/100
23/23 - 0s - loss: 74.2277 - val_loss: 80.3753 - 76ms/epoch - 3ms/step
Epoch 59/100
23/23 - 0s - loss: 72.8257 - val_loss: 79.2777 - 71ms/epoch - 3ms/step
Epoch 60/100
23/23 - 0s - loss: 71.8024 - val_loss: 78.2752 - 70ms/epoch - 3ms/step
Epoch 61/100
23/23 - 0s - loss: 70.4661 - val_loss: 75.5075 - 84ms/epoch - 4ms/step
Epoch 62/100
23/23 - 0s - loss: 69.0351 - val_loss: 74.1913 - 75ms/epoch - 3ms/step
Epoch 63/100
23/23 - 0s - loss: 67.7678 - val_loss: 73.3517 - 67ms/epoch - 3ms/step
Epoch 64/100
23/23 - 0s - loss: 66.3675 - val_loss: 73.1309 - 60ms/epoch - 3ms/step
Epoch 65/100
23/23 - 0s - loss: 65.5434 - val_loss: 71.4194 - 72ms/epoch - 3ms/step
Epoch 66/100
23/23 - 0s - loss: 64.4303 - val_loss: 69.7501 - 65ms/epoch - 3ms/step
Epoch 67/100
23/23 - 0s - loss: 63.5813 - val_loss: 69.0810 - 72ms/epoch - 3ms/step
Epoch 68/100
23/23 - 0s - loss: 63.1475 - val_loss: 68.7303 - 58ms/epoch - 3ms/step
Epoch 69/100
23/23 - 0s - loss: 61.5750 - val_loss: 67.4965 - 60ms/epoch - 3ms/step
Epoch 70/100
23/23 - 0s - loss: 61.1552 - val_loss: 66.3192 - 59ms/epoch - 3ms/step
Epoch 71/100
23/23 - 0s - loss: 59.9827 - val_loss: 65.1117 - 66ms/epoch - 3ms/step
Epoch 72/100
23/23 - 0s - loss: 59.7288 - val_loss: 64.9181 - 75ms/epoch - 3ms/step
Epoch 73/100
23/23 - 0s - loss: 58.9107 - val_loss: 64.1645 - 74ms/epoch - 3ms/step
Epoch 74/100
23/23 - 0s - loss: 58.0944 - val_loss: 63.0866 - 76ms/epoch - 3ms/step
Epoch 75/100
23/23 - 0s - loss: 57.3573 - val_loss: 62.4512 - 77ms/epoch - 3ms/step
Epoch 76/100
23/23 - 0s - loss: 56.6682 - val_loss: 62.0529 - 59ms/epoch - 3ms/step
Epoch 77/100
23/23 - 0s - loss: 56.2308 - val_loss: 61.4679 - 62ms/epoch - 3ms/step
Epoch 78/100
23/23 - 0s - loss: 55.2717 - val_loss: 60.3217 - 65ms/epoch - 3ms/step
Epoch 79/100
23/23 - 0s - loss: 54.8520 - val_loss: 60.4640 - 71ms/epoch - 3ms/step
Epoch 80/100
23/23 - 0s - loss: 54.2359 - val_loss: 59.5273 - 64ms/epoch - 3ms/step
Epoch 81/100
23/23 - 0s - loss: 53.6644 - val_loss: 58.7857 - 74ms/epoch - 3ms/step
Epoch 82/100
23/23 - 0s - loss: 53.2852 - val_loss: 58.6325 - 74ms/epoch - 3ms/step
Epoch 83/100
23/23 - 0s - loss: 52.5409 - val_loss: 57.9868 - 82ms/epoch - 4ms/step
Epoch 84/100
23/23 - 0s - loss: 51.9107 - val_loss: 57.0780 - 64ms/epoch - 3ms/step
Epoch 85/100
23/23 - 0s - loss: 51.4098 - val_loss: 57.0889 - 66ms/epoch - 3ms/step
Epoch 86/100
23/23 - 0s - loss: 51.3653 - val_loss: 57.3708 - 77ms/epoch - 3ms/step
Epoch 87/100
23/23 - 0s - loss: 50.8021 - val_loss: 55.2696 - 70ms/epoch - 3ms/step
Epoch 88/100
23/23 - 0s - loss: 50.3590 - val_loss: 55.6799 - 67ms/epoch - 3ms/step
Epoch 89/100
23/23 - 0s - loss: 49.8661 - val_loss: 54.4219 - 67ms/epoch - 3ms/step
Epoch 90/100
23/23 - 0s - loss: 49.2355 - val_loss: 54.5084 - 68ms/epoch - 3ms/step
Epoch 91/100
23/23 - 0s - loss: 48.8296 - val_loss: 54.5189 - 70ms/epoch - 3ms/step
Epoch 92/100
23/23 - 0s - loss: 48.3788 - val_loss: 53.5330 - 59ms/epoch - 3ms/step
Epoch 93/100
23/23 - 0s - loss: 48.2307 - val_loss: 54.5813 - 75ms/epoch - 3ms/step
Epoch 94/100
23/23 - 0s - loss: 47.8594 - val_loss: 53.2942 - 69ms/epoch - 3ms/step
Epoch 95/100
23/23 - 0s - loss: 47.1891 - val_loss: 53.3435 - 60ms/epoch - 3ms/step
Epoch 96/100
23/23 - 0s - loss: 46.7501 - val_loss: 52.1574 - 72ms/epoch - 3ms/step
Epoch 97/100
23/23 - 0s - loss: 46.2826 - val_loss: 52.7645 - 74ms/epoch - 3ms/step
Epoch 98/100
23/23 - 0s - loss: 46.0792 - val_loss: 52.2655 - 70ms/epoch - 3ms/step
Epoch 99/100
23/23 - 0s - loss: 45.6107 - val_loss: 51.7980 - 71ms/epoch - 3ms/step
Epoch 100/100
23/23 - 0s - loss: 45.2739 - val_loss: 51.2141 - 71ms/epoch - 3ms/step

In [96]:
from sklearn.metrics import mean_squared_error
y_pred = model.predict(X_test)
mean_squared_error(y_test, y_pred)

51.21409919498688